

# ------------------------------ Shared params ------------------------------
use_pretrained_mask: False

# -------------------------------- Stage 1: Pixel-wise --------------------------------
# Depth network architecture
device: 'cuda'
depth_net_type: 'diffnet'
pose_net_type: 'diffnet'
# Dataloading
height: 192
width: 512
img_ext: "png"
train_data_dir: "./data/cityscapes/citiscapes_512x1024"
train_file_path: "./splits/cityscapes_preprocessed/train_files.txt"
val_data_dir: "./data/cityscapes/cityscapes_val_512x1024"
val_file_path: "./splits/cityscapes_preprocessed/val_files.txt"

val_depth_data_dir: "./data/cityscapes/leftImg8bit_sequence"
val_depth_file_path: "./splits/cityscapes/val_files.txt"
val_gt_depth_path: "./data/cityscapes/gt_depths/val_gt_depths"
val_gt_mask_path: "./data/cityscapes/gt_dynamic_object_mask/val_mask_class"

test_depth_data_dir: "./data/cityscapes/leftImg8bit_sequence"
test_depth_file_path: "./splits/cityscapes/test_files.txt"
test_gt_depth_path: "./data/cityscapes/gt_depths/test_gt_depths"
test_gt_mask_path: "./data/cityscapes/gt_dynamic_object_mask/test_mask_class"
# Training setting
nb_gpus: 1
# Logging
log_path: "./checkpoints/citiscapes/diffnet_predMask"
pixelwise_depthnet_load_weights_folder: null

# -------------------------------- Stage 1.1: Slot Attention --------------------------------
# Dataset parameters
sa_epochs: 40
sa_flow_threshold: 1.0
sa_extracted_mask_threshold: 0.25
sa_batch_size: 16
slot_height: 128
slot_width: 128
# Model parameters
sa_in_channels: 4
sa_out_channels: 4
sa_num_slots: 5
sa_num_iterations: 3
sa_empty_cache: true
# Loss parameters
sa_z_loss_w_max: 0.002
sa_z_loss_w_min: 0.000
sa_z_loss_w_start_steps: 20000
sa_z_loss_w_end_steps: 120000
sa_recons_loss_w: 1.0
sa_flow_recons_loss_w: 1.0
sa_depth_recons_loss_w: 0.2
sa_bg_mask_loss_w: 0.005
sa_bg_recon_loss_w: 1.0
sa_bg_mask_loss_epoch: 5
sa_bg_recon_loss_epoch: 5
# Optimizer parameters
sa_lr: 0.0004
sa_warmup_steps_pct: 0.02
sa_decay_steps_pct: 0.2
sa_weight_decay: 0.0
sa_scheduler_gamma: 0.5
sa_eval_step: 2000
sa_global_step: 0
sa_slot_attention_load_weights_folder: null

# ------------------------------ Stage 1.2: Ground Segmentation ------------------------------
# Training params
gs_lr: 0.001
gs_use_depth: true
gs_batch_size: 16
gs_eval_step: 1000
gs_epochs: 20
gs_reduce_lr_epoch: [5, 15]
# Loss params
gs_suppressed_road_mask_loss_weight: 0.25
gs_self_supervision_loss_weight: 0.5
gs_smooth_loss_weight: 2
gs_do_self_supervision: true
gs_start_self_supervision_step: 17500
gs_use_full_self_supervision_loss_step: 22500
gs_start_supress_noisy_mask_signal_step: 45000
gs_end_supress_noisy_mask_signal_step: 50000
ground_segmentation_load_weights_folder: null

# ------------------------------- Stage 1.3: Object Detection --------------------------------
# Training params
od_flow_threshold: 1.0
od_object_size_threshold: 0.001
od_num_epochs: 10
od_batch_size: 16
od_num_workers: 4
od_eval_step: 1000
od_do_self_supervise: true
od_mask_size_threshold: 0.001
od_self_supervise_score_threshold_dict: {1: 0.5, 2: 0.55, 3: 0.55, 4: 0.6, 5: 0.6, 6: 0.65, 7: 0.65, 8: 0.7, 9: 0.7}
od_processed_mask_epochs: [2, 4, 7, 9]
od_mask_augmentation_epochs: [9]
object_detection_load_weights_folder: null

# -------------------------------- Stage 2: Object depthnet --------------------------------
object_depthnet_load_weights_folder: null

# --------------------------------------- Evaluation ---------------------------------------
eval_model_load_path: null